### PR TITLE
XPM: Support `const` keyword in array type

### LINKED ISSUE #36: XPM decoder doesn't work with ImageMagick output
Information

```shell
$ uname -r
6.8.0-100-generic
$ cat /etc/os-release | grep VERSION
VERSION_ID="24.04"
VERSION="24.04.3 LTS (Noble Numbat)"
VERSION_CODENAME=noble"
$ convert --version
Version: ImageMagick 6.9.12-98 Q16 x86_64 18038 https://legacy.imagemagick.org
Copyright: (C) 1999 ImageMagick Studio LLC
License: https://imagemagick.org/script/license.php
Features: Cipher DPC Modules OpenMP(4.5) 
Delegates (built-in): bzlib djvu fftw fontconfig freetype heic jbig jng jp2 jpeg lcms lqr ltdl lzma openexr pangocairo png raw tiff webp wmf x xml zlib
```

When converting a basic image into xpm format

```
$ convert smpte.jpeg smpte.xpm
$ file smpte.jpg 
smpte.jpg: JPEG image data, JFIF standard 1.01, aspect ratio, density 300x300, segment length 16, baseline, precision 8, 512x384, components 3
$ file smpte.xpm
smpte.xpm: X pixmap image text, 512 x 384 x 145, 2 chars/pixel
$ file --version
file-5.45
magic file from /etc/magic:/usr/share/misc/magic
```

I see no error, GNU-magic correctly detects that everything. The internal `xpm` reader fails with `called `Result::unwrap()` on an `Err` value: Format error decoding `XPM`: Failed to parse array definition, at byte=19,line=2:col=9`

# Minimal reproduction

The rust code is the following:

```rust
const XPM_DATA = include!("smpte.xpm");

fn main() -> anyhow::Result<()> {
    let _ = image_extras::xpm::XpmDecoder::new(std::io::Cursor::new(XPM_DATA))?;
    Ok(())
}
```

This was reproduced using: `version = "0.1.0"` & `image = 0.25.9` & `anyhow=1.0.101` (out of lethargy).

# Test Data

<details>
  <summary>Test Data</summary>

Image

[smpte.xpm.txt](https://github.com/user-attachments/files/25318545/smpte.xpm.txt)

  
</details>

### PR DESCRIPTION
**Pull request by RunDevelopment**
fixes #36

The sample file from #36 contained the `const` keyword, which our parser didn't support. See the user-provided sample file:

```c
/* XPM */
static const char *smpte[] = {
```

(And [here's the code in ImageMagick](https://github.com/ImageMagick/ImageMagick/blob/0be03b009e7158e24b61786d684d2e467a8dcb30/coders/xpm.c#L837-L840) that generated this text.)

So I added support for arrays with a type of `const char*` and not just plain `char*`.

I also added a new reference test image. It's the same file as `green.xpm`, I just changed the array line to `static const char *smpte[] = {`.

---

@mstoeckl As the author of the XPM parser, could you please review this?

### CODE REVIEW

File: src/xpm/mod.rs [hunk 1]
```diff
@@ -326,6 +326,35 @@ fn fold_to_lower(x: u8) -> u8 {
...
+/// error will be returned.
+fn read_keyword<'buf, R: Iterator<Item = u8>>(
+    r: &mut TextReader<R>,
+    buf: &'buf mut [u8],
+    part: XpmPart,
+) -> Result<&'buf [u8], XpmDecodeError> {
+    let mut len = 0;
+
+    while let Some(b) = r.peek() {
+        if valid_name_char(b) {
```
Comment (mstoeckl) [inline src/xpm/mod.rs]: `valid_name_char` identifies letters that are valid for _color_ names, including "#" and numbers. Since the value that `read_keyword` stores to `buf` is only tested against `char` and `const`, it doesn't matter for the correctness of the parser, but it does make the function description inaccurate.

File: src/xpm/mod.rs [hunk 2]
```diff
@@ -660,17 +701,27 @@ fn parse_color(data: &[u8]) -> Result<[u16; 4], XpmDecodeError> {
...
     read_to_newline(r, XpmPart::Header)?;
 
     skip_whitespace_and_comments(r, XpmPart::ArrayStart)?;
     read_fixed_string(r, b"static", XpmPart::ArrayStart)?;
-    if skip_whitespace_and_comments(r, XpmPart::ArrayStart)? == 0 {
-        /* need a space or other char between 'static' and 'char' */
-        return Err(XpmDecodeError::Parse(XpmPart::ArrayStart, r.loc()));
+    skip_non_empty_whitespace_and_comments(r, XpmPart::ArrayStart)?;
+
+    // there may be an optional "const" keyword before "char"
```
Comment (mstoeckl) [inline src/xpm/mod.rs]: It might be helpful to mention that optional `const` keyword is something recently introduced by ImageMagick and which is not in the original XPM spec. (So that in the distant future, if we _do_ need a "strict" parsing mode, it is easier to identify all deviations.)

**Comment by RunDevelopment** [comment]
Thanks for the review, @mstoeckl! I addressed your comments. Please take a look again.
